<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Domain\Agents\" />
    <Folder Include="Domain\Constants\" />
    <Folder Include="Domain\Requests\" />
  </ItemGroup>

</Project>
